-- Initial migration for Telegram Casino
-- This file is auto-generated by Drizzle Kit

-- Create extension for UUID generation
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Create users table
CREATE TABLE IF NOT EXISTS "users" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"telegram_id" bigint NOT NULL,
	"username" text,
	"first_name" text,
	"last_name" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "users_telegram_id_unique" UNIQUE("telegram_id")
);

-- Create sessions table
CREATE TABLE IF NOT EXISTS "sessions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"jwt_id" text NOT NULL,
	"expires_at" timestamp NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "sessions_jwt_id_unique" UNIQUE("jwt_id")
);

-- Create balances table
CREATE TABLE IF NOT EXISTS "balances" (
	"user_id" uuid PRIMARY KEY NOT NULL,
	"available" bigint DEFAULT 0 NOT NULL,
	"locked" bigint DEFAULT 0 NOT NULL,
	"currency" text DEFAULT 'CREDITS' NOT NULL
);

-- Create transactions table
CREATE TABLE IF NOT EXISTS "transactions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"type" text NOT NULL,
	"amount" bigint NOT NULL,
	"meta" jsonb,
	"created_at" timestamp DEFAULT now() NOT NULL
);

-- Create server_seeds table
CREATE TABLE IF NOT EXISTS "server_seeds" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"hash" text NOT NULL,
	"revealed_seed" text,
	"active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"rotated_at" timestamp
);

-- Create client_seeds table
CREATE TABLE IF NOT EXISTS "client_seeds" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"seed" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);

-- Create bets table
CREATE TABLE IF NOT EXISTS "bets" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"game" text NOT NULL,
	"amount" bigint NOT NULL,
	"result" text NOT NULL,
	"profit" bigint NOT NULL,
	"nonce" integer NOT NULL,
	"server_seed_id" uuid NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);

-- Create dice_bets table
CREATE TABLE IF NOT EXISTS "dice_bets" (
	"bet_id" uuid PRIMARY KEY NOT NULL,
	"side" text NOT NULL,
	"target" numeric(5, 2) NOT NULL,
	"roll" numeric(5, 2) NOT NULL,
	"payout_multiplier" numeric(10, 8) NOT NULL
);

-- Create slot_spins table
CREATE TABLE IF NOT EXISTS "slot_spins" (
	"bet_id" uuid PRIMARY KEY NOT NULL,
	"reels" jsonb NOT NULL,
	"paylines_hit" integer NOT NULL,
	"payout" bigint NOT NULL
);

-- Create crash_rounds table
CREATE TABLE IF NOT EXISTS "crash_rounds" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"server_seed_id" uuid NOT NULL,
	"hash" text NOT NULL,
	"start_at" timestamp,
	"end_at" timestamp,
	"crash_point" numeric(10, 8),
	"status" text DEFAULT 'PENDING' NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);

-- Create crash_cashes table
CREATE TABLE IF NOT EXISTS "crash_cashes" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"round_id" uuid NOT NULL,
	"user_id" uuid NOT NULL,
	"cashout_multiplier" numeric(10, 8) NOT NULL,
	"amount" bigint NOT NULL,
	"profit" bigint NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);

-- Add foreign key constraints
DO $$ BEGIN
 ALTER TABLE "sessions" ADD CONSTRAINT "sessions_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
 ALTER TABLE "balances" ADD CONSTRAINT "balances_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
 ALTER TABLE "transactions" ADD CONSTRAINT "transactions_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
 ALTER TABLE "client_seeds" ADD CONSTRAINT "client_seeds_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
 ALTER TABLE "bets" ADD CONSTRAINT "bets_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
 ALTER TABLE "bets" ADD CONSTRAINT "bets_server_seed_id_server_seeds_id_fk" FOREIGN KEY ("server_seed_id") REFERENCES "server_seeds"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
 ALTER TABLE "dice_bets" ADD CONSTRAINT "dice_bets_bet_id_bets_id_fk" FOREIGN KEY ("bet_id") REFERENCES "bets"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
 ALTER TABLE "slot_spins" ADD CONSTRAINT "slot_spins_bet_id_bets_id_fk" FOREIGN KEY ("bet_id") REFERENCES "bets"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
 ALTER TABLE "crash_rounds" ADD CONSTRAINT "crash_rounds_server_seed_id_server_seeds_id_fk" FOREIGN KEY ("server_seed_id") REFERENCES "server_seeds"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
 ALTER TABLE "crash_cashes" ADD CONSTRAINT "crash_cashes_round_id_crash_rounds_id_fk" FOREIGN KEY ("round_id") REFERENCES "crash_rounds"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
 ALTER TABLE "crash_cashes" ADD CONSTRAINT "crash_cashes_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;

-- Add constraints for enum fields
ALTER TABLE "transactions" ADD CONSTRAINT "transactions_type_check" CHECK ("type" IN ('DEPOSIT', 'WITHDRAW', 'BET', 'PAYOUT', 'REFUND'));
ALTER TABLE "bets" ADD CONSTRAINT "bets_game_check" CHECK ("game" IN ('DICE', 'SLOTS', 'CRASH'));
ALTER TABLE "bets" ADD CONSTRAINT "bets_result_check" CHECK ("result" IN ('WIN', 'LOSE', 'CASHED'));
ALTER TABLE "dice_bets" ADD CONSTRAINT "dice_bets_side_check" CHECK ("side" IN ('UNDER', 'OVER'));
ALTER TABLE "crash_rounds" ADD CONSTRAINT "crash_rounds_status_check" CHECK ("status" IN ('PENDING', 'RUNNING', 'ENDED'));

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS "idx_users_telegram_id" ON "users" ("telegram_id");
CREATE INDEX IF NOT EXISTS "idx_sessions_user_id" ON "sessions" ("user_id");
CREATE INDEX IF NOT EXISTS "idx_sessions_expires_at" ON "sessions" ("expires_at");
CREATE INDEX IF NOT EXISTS "idx_transactions_user_id" ON "transactions" ("user_id");
CREATE INDEX IF NOT EXISTS "idx_transactions_created_at" ON "transactions" ("created_at");
CREATE INDEX IF NOT EXISTS "idx_bets_user_id" ON "bets" ("user_id");
CREATE INDEX IF NOT EXISTS "idx_bets_created_at" ON "bets" ("created_at");
CREATE INDEX IF NOT EXISTS "idx_server_seeds_active" ON "server_seeds" ("active");
CREATE INDEX IF NOT EXISTS "idx_client_seeds_user_id" ON "client_seeds" ("user_id");
CREATE INDEX IF NOT EXISTS "idx_crash_rounds_status" ON "crash_rounds" ("status");
CREATE INDEX IF NOT EXISTS "idx_crash_rounds_created_at" ON "crash_rounds" ("created_at");
CREATE INDEX IF NOT EXISTS "idx_crash_cashes_round_id" ON "crash_cashes" ("round_id");
CREATE INDEX IF NOT EXISTS "idx_crash_cashes_user_id" ON "crash_cashes" ("user_id");
